### ISSUE TITLE
Make captcha simple

### ISSUE THREAD

**Issue by smthngslv** [innonymous/api-server#5]
Sometimes captcha cannot be solved fast

**Comment by sevenzing** [comment]
@smthngslv what do you think about way to fix it? I see two options:
+ Cange the way we select characters for catcha (maybe decrease length? or reduce the alphabet?)
+ Cange the way image is created (find something in `captcha` library)

**Comment by smthngslv** [comment]
> @smthngslv what do you think about way to fix it? I see two options:
> 
> * Cange the way we select characters for catcha (maybe decrease length? or reduce the alphabet?)
> * Cange the way image is created (find something in `captcha` library)

I guess we can use all English letters and 8 numbers (1 and 7 are too similar). Now the value of captcha is 4 bytes long (8 hex symbols), so we can reduce it to 4 symbols and add TTL for captcha like 5 minutes
